# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.kaiser.com:
    container_name: orderer.kaiser.com
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # Kafka
      - ORDERER_KAFKA_RETRY_SHORTINTERVAL=1s
      - ORDERER_KAFKA_RETRY_SHORTTOTAL=30s
      - ORDERER_KAFKA_VERBOSE=true
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/kaiser.com/orderers/orderer.kaiser.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/kaiser.com/orderers/orderer.kaiser.com/tls/:/var/hyperledger/orderer/tls
    ports:
      - 7050:7050

  peer0.KProvider.kaiser.com:
    container_name: peer0.KProvider.kaiser.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.KProvider.kaiser.com
      - CORE_PEER_ADDRESS=peer0.KProvider.kaiser.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.KProvider.kaiser.com:7051
      - CORE_PEER_LOCALMSPID=KProviderMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/KProvider.kaiser.com/peers/peer0.KProvider.kaiser.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/KProvider.kaiser.com/peers/peer0.KProvider.kaiser.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7051:7051
      - 7053:7053

  peer1.KProvider.kaiser.com:
    container_name: peer1.KProvider.kaiser.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.KProvider.kaiser.com
      - CORE_PEER_ADDRESS=peer1.KProvider.kaiser.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.KProvider.kaiser.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.KProvider.kaiser.com:7051
      - CORE_PEER_LOCALMSPID=KProviderMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/KProvider.kaiser.com/peers/peer1.KProvider.kaiser.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/KProvider.kaiser.com/peers/peer1.KProvider.kaiser.com/tls:/etc/hyperledger/fabric/tls

    ports:
      - 8051:7051
      - 8053:7053

  peer2.KProvider.kaiser.com:
    container_name: peer2.KProvider.kaiser.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer2.KProvider.kaiser.com
      - CORE_PEER_ADDRESS=peer2.KProvider.kaiser.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.KProvider.kaiser.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.KProvider.kaiser.com:7051
      - CORE_PEER_LOCALMSPID=KProviderMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/KProvider.kaiser.com/peers/peer2.KProvider.kaiser.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/KProvider.kaiser.com/peers/peer2.KProvider.kaiser.com/tls:/etc/hyperledger/fabric/tls

    ports:
      - 8061:7051
      - 8063:7053

  peer3.KProvider.kaiser.com:
    container_name: peer3.KProvider.kaiser.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer3.KProvider.kaiser.com
      - CORE_PEER_ADDRESS=peer3.KProvider.kaiser.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer3.KProvider.kaiser.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.KProvider.kaiser.com:7051
      - CORE_PEER_LOCALMSPID=KProviderMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/KProvider.kaiser.com/peers/peer3.KProvider.kaiser.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/KProvider.kaiser.com/peers/peer3.KProvider.kaiser.com/tls:/etc/hyperledger/fabric/tls

    ports:
      - 8071:7051
      - 8073:7053

  peer4.KPayer.kaiser.com:
    container_name: peer4.KPayer.kaiser.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer4.KPayer.kaiser.com
      - CORE_PEER_ADDRESS=peer4.KPayer.kaiser.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer4.KPayer.kaiser.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer4.KPayer.kaiser.com:7051
      - CORE_PEER_LOCALMSPID=KPayerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/KPayer.kaiser.com/peers/peer4.KPayer.kaiser.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/KPayer.kaiser.com/peers/peer4.KPayer.kaiser.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 9051:7051
      - 9053:7053

  peer5.KPayer.kaiser.com:
    container_name: peer5.KPayer.kaiser.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer5.KPayer.kaiser.com
      - CORE_PEER_ADDRESS=peer5.KPayer.kaiser.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer5.KPayer.kaiser.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer5.KPayer.kaiser.com:7051
      - CORE_PEER_LOCALMSPID=KPayerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/KPayer.kaiser.com/peers/peer5.KPayer.kaiser.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/KPayer.kaiser.com/peers/peer5.KPayer.kaiser.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 10051:7051
      - 10053:7053

  peer6.KPayer.kaiser.com:
    container_name: peer6.KPayer.kaiser.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer6.KPayer.kaiser.com
      - CORE_PEER_ADDRESS=peer6.KPayer.kaiser.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer6.KPayer.kaiser.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer6.KPayer.kaiser.com:7051
      - CORE_PEER_LOCALMSPID=KPayerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/KPayer.kaiser.com/peers/peer6.KPayer.kaiser.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/KPayer.kaiser.com/peers/peer6.KPayer.kaiser.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 10061:7051
      - 10063:7053

  peer7.KPayer.kaiser.com:
    container_name: peer7.KPayer.kaiser.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer7.KPayer.kaiser.com
      - CORE_PEER_ADDRESS=peer7.KPayer.kaiser.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer7.KPayer.kaiser.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer7.KPayer.kaiser.com:7051
      - CORE_PEER_LOCALMSPID=KPayerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/KPayer.kaiser.com/peers/peer7.KPayer.kaiser.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/KPayer.kaiser.com/peers/peer7.KPayer.kaiser.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 10071:7051
      - 10073:7053


